# Generated by Django 5.2.8 on 2026-07-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='text_message',
            field=models.TextField(max_length=200),
        ),
    ]
