# Generated by Django 5.2.8 on 2026-07-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_alter_conversation_id_alter_message_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
