# Generated by Django 5.2.8 on 2026-07-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0008_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='sender',
        ),
    ]
