# Generated by Django 5.2.8 on 2026-07-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0010_message_reciever_alter_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
