# Generated by Django 5.2.8 on 2026-07-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0012_rename_is_seen_notification_is_read_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='messsage',
            new_name='message',
        ),
    ]
